---
- name: Install basics
  become: true
  community.general.pacman:
    state: present
    name:
      - base-devel
      - cmake
      - clang
      - bat
      - ccze
      - lsd
      - ranger
      - fd
      - nmap
