---
- name: Install basics
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - base-devel
    - cmake
    - clang
    - bat
    - ccze
    - lsd
    - ranger
    - fd
    - nmap
