---
- name: Install basics
  become: true
  community.general.pacman:
    state: present
    name:
      # folder/file explore
      # FIXME: may need to move some of them to common task
      - bat
      - lsd
      - yazi
      - fd
      - fzf
      # develop
      - base-devel
      - gdb
      - cmake
      - clang
      - bear # generate compile_commands.json for make projects
      # network
      - nmap
      - curl
      - wget
- name: Make sure fd directory exist
  ansible.builtin.file:
    path: "~/.config/fd"
    state: directory
    mode: u=rwx,g=rx,o=rx
- name: Link fd ignore file
  ansible.builtin.file:
    src: "{{ source_dir }}/roles/common/files/fd/ignore"
    dest: ~/.config/fd/ignore
    state: link
