---
# Configure pacman & install yay
- name: Check if China mirrors ars used
  ansible.builtin.lineinfile:
    path: /etc/pacman.d/mirrorlist
    line: "## Country : China"
    state: present
  check_mode: true
  register: check_mirrors
- name: Read /etc/pacman.d/mirrorlist
  ansible.builtin.slurp:
    src: /etc/pacman.d/mirrorlist
  register: mirrorlist
- name: Use China mirrors if not using
  ansible.builtin.command:
    cmd: pacman-mirrors -c China -m rank
  become: true
  when: mirrorlist['content'] | b64decode | regex_search('^## Country :\ China', multiline=True) is none
  register: china_mirrors
  changed_when: true
# - name: Add archlinuxcn to pacman.conf
#   ansible.builtin.blockinfile:
#     path: /etc/pacman.conf
#     block: |
#       [archlinuxcn]
#       SigLevel = Never
#       Server = https://repo.huaweicloud.com/archlinuxcn/$arch
#   become: true
#   register: archlinuxcn
- name: Refresh packages list
  community.general.pacman:
    update_cache: true
  become: true
  when: china_mirrors.changed or archlinuxcn.changed # noqa: no-handler # see: https://ansible-lint.readthedocs.io/rules/no-handler/
- name: Install archlinuxcn-keyring, yay
  become: true
  community.general.pacman:
    name:
      - archlinuxcn-keyring
      - yay
    state: present
